# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'nova' do
  # Required by RNFirebase
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'

end

